/** Popular free Google Fonts available for accent/typography preferences. */
export const GOOGLE_FONT_FAMILIES = [
  "Abril Fatface",
  "Alegreya",
  "Alegreya Sans",
  "Anton",
  "Archivo",
  "Arimo",
  "Arvo",
  "Asap",
  "Assistant",
  "Barlow",
  "Barlow Condensed",
  "Bebas Neue",
  "Bitter",
  "Cabin",
  "Cairo",
  "Cardo",
  "Catamaran",
  "Caveat",
  "Chivo",
  "Cinzel",
  "Comfortaa",
  "Comic Neue",
  "Cormorant Garamond",
  "Courier Prime",
  "Crimson Pro",
  "Crimson Text",
  "DM Mono",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "Dancing Script",
  "Domine",
  "Dosis",
  "EB Garamond",
  "Exo 2",
  "Fira Code",
  "Fira Sans",
  "Fjalla One",
  "Francois One",
  "Frank Ruhl Libre",
  "Fredoka",
  "Figtree",
  "Gelasio",
  "Gloria Hallelujah",
  "Gothic A1",
  "Great Vibes",
  "Heebo",
  "Hind",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Inconsolata",
  "Indie Flower",
  "Inter",
  "Josefin Sans",
  "Josefin Slab",
  "Jost",
  "Kanit",
  "Karla",
  "Koulen",
  "Lato",
  "Lexend",
  "Libre Baskerville",
  "Libre Franklin",
  "Literata",
  "Lobster",
  "Londrina Solid",
  "Lora",
  "Manrope",
  "Maven Pro",
  "Merriweather",
  "Merriweather Sans",
  "Montserrat",
  "Mukta",
  "Mulish",
  "Nanum Gothic",
  "Neuton",
  "Noto Sans",
  "Noto Serif",
  "Nunito",
  "Nunito Sans",
  "Old Standard TT",
  "Open Sans",
  "Oswald",
  "Outfit",
  "Overpass",
  "Oxygen",
  "PT Sans",
  "PT Serif",
  "Pacifico",
  "Passion One",
  "Patrick Hand",
  "Paytone One",
  "Permanent Marker",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Prompt",
  "Public Sans",
  "Quicksand",
  "Raleway",
  "Red Hat Display",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roboto Slab",
  "Rubik",
  "Ruda",
  "Sacramento",
  "Saira",
  "Schibsted Grotesk",
  "Sen",
  "Shadows Into Light",
  "Signika",
  "Sora",
  "Source Code Pro",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Spectral",
  "Syne",
  "Teko",
  "Titillium Web",
  "Ubuntu",
  "Ubuntu Mono",
  "Unbounded",
  "Varela Round",
  "Vollkorn",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Yeseva One",
  "Zilla Slab",
] as const;

export type GoogleFontFamily = (typeof GOOGLE_FONT_FAMILIES)[number];

export function searchGoogleFonts(query: string, limit = 12) {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return GOOGLE_FONT_FAMILIES.slice(0, limit);
  }

  return GOOGLE_FONT_FAMILIES.filter((family) =>
    family.toLowerCase().includes(normalized),
  ).slice(0, limit);
}

export function isGoogleFontFamily(value: string): value is GoogleFontFamily {
  return (GOOGLE_FONT_FAMILIES as readonly string[]).includes(value);
}
